version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=user_db
    depends_on:
      - mysql_user

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=product_db
    depends_on:
      - mysql_product

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=order_db
    depends_on:
      - mysql_order

  mysql_user:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"

  mysql_product:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: product_db
    ports:
      - "3308:3306"

  mysql_order:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: order_db
    ports:
      - "3309:3306"
