
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-order-pvc
  labels:
    app: mysql-order
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-order-service
  labels:
    app: mysql-order
spec:
  ports:
    - port: 3309
  selector:
    app: mysql-order
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order-deployment
  labels:
    app: mysql-order
spec:
  selector:
    matchLabels:
      app: mysql-order
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-order
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-order
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name: MYSQL_DATABASE
          value: "order_db"
        ports:
        - containerPort: 3309
          name: mysql
        volumeMounts:
        - name: mysql-order-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-order-storage
        persistentVolumeClaim:
          claimName: mysql-order-pvc
