
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-product-pvc
  labels:
    app: mysql-product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-product-service
  labels:
    app: mysql-product
spec:
  ports:
    - port: 3307
  selector:
    app: mysql-product
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product-deployment
  labels:
    app: mysql-product
spec:
  selector:
    matchLabels:
      app: mysql-product
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-product
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-product
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name: MYSQL_DATABASE
          value: "product_db"
        ports:
        - containerPort: 3307
          name: mysql
        volumeMounts:
        - name: mysql-product-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-product-storage
        persistentVolumeClaim:
          claimName: mysql-product-pvc
