apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: MYSQL_HOST
          value: "mysql-order"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: ""
        - name: MYSQL_DB
          value: "order_db"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: order-service
